version: "3.8"
services:
  postgres:
    container_name: "postgres"
    image: "postgres:12-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: covid-timeline
    ports:
      - 5432:5432
    restart: always

  covid-timeline-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - .:/app